version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    php:
        build: ./images/php-fpm
        expose:
            - "9000"
        volumes:
            - ./symfony:/var/www/symfony
        links:
            - db
        environment:
            SYMFONY__DATABASE_PORT: 3306
            SYMFONY__DATABASE_HOST: db
            SYMFONY__DATABASE_NAME: symfony
            SYMFONY__DATABASE_USER: root
            SYMFONY__DATABASE_PASSWORD: root
    
    nginx:
        environment:
            NGINX_HOST: symfony.dev
            NGINX_PORT: 80
            PROJECT_WEBROOT: /var/www/symfony/web
        build: ./images/nginx
        ports:
            - "8800:80"
        links:
            - php